### ISSUE TITLE
Implementation of Folder section

### ISSUE THREAD

**Issue by PrajwalDhule** [bytemakers/Noteslify#133]
### Full implementation of folder section

I want to implement the folder section for this website. I have a basic idea on how I'll go about for both the front and back-end for this. If you are accepting this issue, please assign it to me with a hacktoberfest label, I would really appreciate it :)

![image](https://user-images.githubusercontent.com/89639472/195278617-75f99726-61e8-4c4f-8a3e-71f0858226a4.png)
![image](https://user-images.githubusercontent.com/89639472/195278682-cb401af4-9282-43fe-bf89-d0a026643178.png)

**Comment by devarshishimpi** [comment]
Yes sure. Looks great to me.

**Comment by devarshishimpi** [comment]
You may replace the navbar button above logout button saying as `Folders` and using font awesome icon for the same

**Comment by PrajwalDhule** [comment]
> You may replace the navbar button above logout button saying as `Folders` and using font awesome icon for the same

Yes I will rename it and I don't think I need to add an icon as there is one already

**Comment by devarshishimpi** [comment]
> > You may replace the navbar button above logout button saying as `Folders` and using font awesome icon for the same
> 
> Yes I will rename it and I don't think I need to add an icon as there is one already

That works as well, tho would love if we could get a better icon which matches folders

**Comment by PrajwalDhule** [comment]
> > > You may replace the navbar button above logout button saying as `Folders` and using font awesome icon for the same
> > 
> > 
> > Yes I will rename it and I don't think I need to add an icon as there is one already
> 
> That works as well, tho would love if we could get a better icon which matches folders

Sure

**Comment by PrajwalDhule** [comment]
Hello! I needed some help for this issue. For the backend part of this issue, I made a folder schema but I am having trouble with actually getting it working. This project seems very interesting and I want to contribute as much as I can, but I didn't quite understand API part and how the data is sent and fetched from MongoDB. I tried what I know from one of my previous projects but it still couldn't get the job done. I can complete the frontend part but would appreciate if you could somehow help me better understand and implement the backend. 
Thank you!

**Comment by devarshishimpi** [comment]
To further understand. I have created a branch for the same. Could you create a PR of the frontend-only which merges to that branch?

**Comment by PrajwalDhule** [comment]
> To further understand. I have created a branch for the same. Could you create a PR of the frontend-only which merges to that branch?

Sure, I'll work on that

**Comment by devarshishimpi** [comment]
@PrajwalDhule May I know by when it would be ready??

**Comment by PrajwalDhule** [comment]
> @PrajwalDhule May I know by when it would be ready??

Sorry for the delay, I was busy with my exams. I am almost done with it, will make a PR by midnight

**Comment by devarshishimpi** [comment]
> > @PrajwalDhule May I know by when it would be ready??
> 
> Sorry for the delay, I was busy with my exams. I am almost done with it, will make a PR by midnight

Okay. No worries.

**Comment by Gauravdarkslayer** [comment]
@devarshishimpi Sure.

**Comment by Gauravdarkslayer** [comment]
@devarshishimpi Currently the folders section is not linked with backend. So we need to create folder section APIs accordingly. 
Also some things i noticed in this section:
1. The page is reloading each time in folder section. 
2. Action buttons not aligned properly.
3. Url params not properly sets. 
![image](https://user-images.githubusercontent.com/18503497/199543222-40f4520a-1412-4a9a-a1dd-bd9d6960a28d.png)


![image](https://user-images.githubusercontent.com/18503497/199542587-6335cbe1-7006-49d7-898b-85fab9536afc.png)

CC: @PrajwalDhule

**Comment by devarshishimpi** [comment]
@Gauravdarkslayer Yes, just the frontend was added

**Comment by Gauravdarkslayer** [comment]
@devarshishimpi Is this issue is solved ?
