### ISSUE TITLE
🐛 [BUG] - Max-width in the layout 

### ISSUE THREAD

**Issue by nirajpdn** [bytemakers/Noteslify#186]
### Description

In wider screen the layout is not good as expected design wise and the components in the navbar and footer are not aligned properly.
So, max-width can be a better to use.

### Reproduction URL

https://noteslify.stonecss.com

### Reproduction steps

```bash
1. Go to `https://noteslify.stonecss.com`
2. Decrease the browser zoom
```

### Screenshots

```bash
![Navbar](https://user-images.githubusercontent.com/59108522/197906634-eadcbcba-199b-4778-85a2-75e757dd8777.png)

![Footer](https://user-images.githubusercontent.com/59108522/197906742-e28c2829-d63f-4007-afa7-1bd62e151203.png)
```

### Browsers

Chrome

### OS

Mac

**Comment by devarshishimpi** [comment]
Thanks For Notifying!! Would you like to contribute to the same as well?

**Comment by nirajpdn** [comment]
@devarshishimpi sure. Happy to contribute again.

**Comment by devarshishimpi** [comment]
> @devarshishimpi sure. Happy to contribute again.

Okay, have assigned

**Comment by devarshishimpi** [comment]
@nirajpdn Done with the same? Do keep in sync with the repo commits

**Comment by nirajpdn** [comment]
> @nirajpdn Done with the same? Do keep in sync with the repo commits

I am syncing upstream. Thanks. Will push very soon

**Comment by rbeaujon** [comment]
This issue is already done or are you waiting for something more to do here? Thank you

**Comment by devarshishimpi** [comment]
Yep, just apart from specific mobile sizes

**Comment by rbeaujon** [comment]
The responsive part is someone working on?

**Comment by devarshishimpi** [comment]
No one at the moment

**Comment by rbeaujon** [comment]
l'll work on that

**Comment by devarshishimpi** [comment]
Okay, Have assigned you

**Comment by rbeaujon** [comment]
Do you have some considerations that I've to take to work on this?

**Comment by devarshishimpi** [comment]
Closed
