### ISSUE TITLE
Adding Pricing Page

### ISSUE THREAD

**Issue by devarshishimpi** [bytemakers/Noteslify#206]

**Comment by mani-rsg** [comment]
Hi, @devarshishimpi  do we have any mocks for this? so that I can work on

**Comment by devarshishimpi** [comment]
> Hi, @devarshishimpi do we have any mocks for this? so that I can work on

There are 3 tiers to be made

1. Free Open Source
2. Coming Soon
3. Enterprise

You can make according to this with few lorem ipsum fields above it

For example Gitpod's Pricing Plans

![image](https://user-images.githubusercontent.com/43378923/198827860-00a36f14-26d9-4873-81e3-e048f5e611ca.png)

**Comment by devarshishimpi** [comment]
@mani-rsg updates on this??

**Comment by mani-rsg** [comment]
Hey Sorry, didn't get time to work on this due to office work. Sorry for the inconvenience thereby. Someone else can start working

**Comment by devarshishimpi** [comment]
Okay no worries

**Comment by Dun-sin** [comment]
I can help with this if you would like @devarshishimpi

**Comment by devarshishimpi** [comment]
Sure

**Comment by devarshishimpi** [comment]
Completed.
