### ISSUE TITLE
Create React-Native Based Mobile App

### ISSUE THREAD

**Issue by devarshishimpi** [bytemakers/Noteslify#208]

**Comment by nmathew98** [comment]
hi can I be assigned to this issue?

**Comment by devarshishimpi** [comment]
Sure, make sure to build it in `apps/mobile` directory

**Comment by nmathew98** [comment]
> Sure, make sure to build it in `apps/mobile` directory

will push something out tomorrow. Just scaffolding I'm guessing no pages or anything yet?

**Comment by devarshishimpi** [comment]
Okay
