### ISSUE TITLE
💡 [REQUEST] - Sending all the 500 status codes error to email

### ISSUE THREAD

**Issue by Gauravdarkslayer** [bytemakers/Noteslify#215]
### Summary

Need a feature in backend application i.e. whenever there is an 500 internal server error caused in backend then it should send an email to admin mentioning whole stacktrace.
This will help us to monitor our app better.

### Basic Example

Add error logging to global level.

### Drawbacks

None

**Comment by thevinitgupta** [comment]
@devarshishimpi I would love to work on this.

**Comment by devarshishimpi** [comment]
Sure @thevinitgupta Have assigned you the same. 🚀

**Comment by thevinitgupta** [comment]
Thanks, I'll start working on this.
Is there any particular library you would like me to use for sending the email or should I use `nodemailer`?

**Comment by devarshishimpi** [comment]
> Thanks, I'll start working on this. Is there any particular library you would like me to use for sending the email or should I use `nodemailer`?

Yes `nodemailer` itself

**Comment by devarshishimpi** [comment]
Added
