### ISSUE TITLE
🐛 [BUG] – Unresponsive Navigation Bar

### ISSUE THREAD

**Issue by Dun-sin** [bytemakers/Noteslify#225]
### Description

— Active bubble doesn't fit the navigation bar icon
— Icons are overflowed in the navigation bar 

### Reproduction steps

```bash
1. sign in
2. look at the dashboard.
```

### Screenshots
![Unresponsive navigation bar](https://user-images.githubusercontent.com/78784850/200630836-1002d415-4663-4b42-820b-fd1694d45c30.png)

### Browsers

Firefox

### OS

Windows

**Comment by Dun-sin** [comment]
> @Dun-sin Thanks For Reporting!! Could you specify the screen size?? Looks good on my end ![image](https://user-images.githubusercontent.com/43378923/200634222-7e51fb04-6082-4f61-8749-4c35dc14222d.png)

1366px × 654px

**Comment by devarshishimpi** [comment]
Still can't find any issues with that size 
![image](https://user-images.githubusercontent.com/43378923/200637352-c2a4254a-262b-4656-987c-0d8f068b7c94.png)

**Comment by Dun-sin** [comment]
> Still can't find any issues with that size ![image](https://user-images.githubusercontent.com/43378923/200637352-c2a4254a-262b-4656-987c-0d8f068b7c94.png)

do you use Firefox too? This seems like a weird bug, I tried refreshing the page a few times in case, i should probably check on a different browser and report back to you.

**Comment by Dun-sin** [comment]
Strangely it's just Firefox mine anyway with #227

**Comment by devarshishimpi** [comment]
I see, it's a valid issue. The previous one I did was in Brave.
Checked in Firefox. Maybe something to do with the extra scroll bar coming on the right side of the side nav.

![image](https://user-images.githubusercontent.com/43378923/200639942-e4201a29-3008-41cc-b971-1525ab767618.png)

**Comment by devarshishimpi** [comment]
> Strangely it's just Firefox mine anyway with #227

The dark theme is an issue everywhere, not just with firefox as till now it's been added only in the side nav ( that too partially ) . Implementation is still in progress.

**Comment by Dun-sin** [comment]
> > Strangely it's just Firefox mine anyway with #227
> 
> The dark theme is an issue everywhere, not just with firefox as till now it's been added only in the side nav ( that too partially ) . Implementation is still in progress.

okay fair

**Comment by devarshishimpi** [comment]
Issue made part of https://github.com/bytemakers/Noteslify/issues/237
