### ISSUE TITLE
💡 [REQUEST] - Custom Modal for confirmation

### ISSUE THREAD

**Issue by Dun-sin** [bytemakers/Noteslify#226]
### Summary

Every browser has its way of showing the confirmation modal, which doesn't fit the theme of the project/website
![image](https://user-images.githubusercontent.com/78784850/200634272-7b22b6f8-5897-49a1-8c3e-fd51e3281807.png)

### Basic Example

Instead of the default modal when delete note is clicked, we show the custom modal we create

**Comment by devarshishimpi** [comment]
Definitely!!

**Comment by RakibRahman** [comment]
@devarshishimpi can you assign this to me?

**Comment by devarshishimpi** [comment]
Sure

**Comment by RakibRahman** [comment]
@devarshishimpi Thanks. Should I use custom-made modal or any particular library? Any design guidelines will be appreciated.

**Comment by devarshishimpi** [comment]
Probably just a custom-made modal box
