### ISSUE TITLE
Switching UI to Tailwind

### ISSUE THREAD

**Issue by devarshishimpi** [bytemakers/Noteslify#237]
Currently, the UI/Frontend is based on plain CSS. We will be shifting to using tailwind instead.
Plain CSS `/apps/web/frontend` directory
Tailwind CSS ( New ) `/apps/web/frontendnew` directory
We will be shifting all the pages to be based on tailwind shortly. You can let me know if you would want to work on this as well

Figma file: https://www.figma.com/file/8SygBEU8Mz83pXXNq02sTf/Noteslify-(Notes-UI)?node-id=0%3A1&t=VfEexVnENXVhZIgp-1

**Comment by princehabeeb** [comment]
I will love to contribute to this. i want to put my tailwindcss knowledge to practice

**Comment by devarshishimpi** [comment]
Sure

**Comment by SattyamSamania** [comment]
Hey @devarshishimpi if the issue is still open can I work on this. Please tell further what to do next.

**Comment by devarshishimpi** [comment]
> Hey @devarshishimpi if the issue is still open can I work on this. Please tell further what to do next.

Yes it's still open, basically we have to shift all of the landing page content to a tailwind based new and better landing page, the first issue description has where the folder is present.

**Comment by devarshishimpi** [comment]
@SattyamSamania @princehabeeb @ann0nip Do keep in update with the latest changes 😄 Changes were made to the new landing page, so do sync your repo.

**Comment by princehabeeb** [comment]
> Sure, Have assigned you

Alright. thanks so much

**Comment by SattyamSamania** [comment]
> @SattyamSamania @princehabeeb @ann0nip Do keep in update with the latest changes 😄 Changes were made to the new landing page, so do sync your repo.

Sure @devarshishimpi

**Comment by thevinitgupta** [comment]
Are there any issues open currently for the Tailwind CSS shift?

**Comment by devarshishimpi** [comment]
> Are there any issues open currently for the Tailwind CSS shift?

Yes indeed. https://github.com/bytemakers/Noteslify/issues/37 You can check this, seems like no response from the person who is assigned to this. And yes, new login and signup pages to be made in tailwind as well.

**Comment by thevinitgupta** [comment]
@devarshishimpi I have made a PR for issue #37 and would love to work on the new login and signup pages.

**Comment by devarshishimpi** [comment]
@thevinitgupta Yes it's merged and you can definitely work on the login and sign-up page!

**Comment by devarshishimpi** [comment]
For everyone who is new here. We are building the new Noteslify UI in `/frontendnew` using TailwindCSS!

**Comment by thevinitgupta** [comment]
@devarshishimpi I am not able to work on this currently. Please unassign me.

**Comment by devarshishimpi** [comment]
> @devarshishimpi I am not able to work on this currently. Please unassign me.

No worries!

**Comment by devarshishimpi** [comment]
Please find the Figma file here https://www.figma.com/file/8SygBEU8Mz83pXXNq02sTf/Noteslify-(Notes-UI)?node-id=0%3A1&t=VfEexVnENXVhZIgp-1

**Comment by geeky-sambhav** [comment]
I would also like to contribute on this issue

**Comment by devarshishimpi** [comment]
Sure! @geeky-sambhav I have assigned you the issue

**Comment by d-a-ve** [comment]
Hi, any issues open on the switch to tailwind? Or any page that needs to be developed?

**Comment by kraggy09** [comment]
I would love to do contribute my TailwindCSS knowledge. Can u assign me

**Comment by afzal-adam** [comment]
Hey Guys!!, I would love to contribute.

**Comment by Arzzam** [comment]
Is this issue, still open, can I work on this? 
I would love to work on front end

**Comment by Ayushhgupta39** [comment]
Hi, I would like to work on the tailwind migration. Can you please let me know where I can start?

**Comment by FazeenIjaz** [comment]
Hi,@[devarshishimpi](https://github.com/devarshishimpi)  any issues open on the switch to tailwind? Or any page that needs to be developed? I would to work on that
