### ISSUE TITLE
🐛 [BUG] - No change in button upon hovering

### ISSUE THREAD

**Issue by rohinish404** [bytemakers/Noteslify#266]
### Description

Whenever, the subscribe button is hovered there is no change in the button by while the user will know that they are hovering over the button. It feels like the button is doing nothing. I think the cursor should be changed to pointer and the bg and text colours should be changed.

https://user-images.githubusercontent.com/92542124/213279863-de2ac458-1e88-4f10-a3b0-706fdedb44f2.mov

### Reproduction URL

https://github.com/rohinish404/Noteslify

### Reproduction steps

```bash
1. Go to home page
2. Scroll down to subscribe to newsletter.
3. Hover on the subscribe button.
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Browsers

Chrome

### OS

Mac

**Comment by devarshishimpi** [comment]
Hi @rohinish404 Thanks For opening the issue, actually the frontend UI has been deprecated, there's a new version for the frontend being developed here https://github.com/bytemakers/Noteslify/issues/237 using Tailwind
I am closing this issue, you'll find more info in the above issue about the new version being developed!!
