### ISSUE TITLE
🐛 [BUG] - Navbar not staying fixed

### ISSUE THREAD

**Issue by rohinish404** [bytemakers/Noteslify#271]
### Description

When we scroll down the navbar doesn't stay fixed and moves up. So i think it'll be better for navigation to different sections of the webpage if the navbar stays fixed.
<img width="1435" alt="Screenshot 2023-01-31 at 12 23 49 AM" src="https://user-images.githubusercontent.com/92542124/215568760-5123a76a-0aff-4f34-ba22-14970cab75ea.png">

### Reproduction URL

https://github.com/rohinish404/Noteslify

### Reproduction steps

```bash
1. Go to Home page.
2. Scroll down
3. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Browsers

Chrome

### OS

Mac

**Comment by aamirxshaikh** [comment]
Hi, I would like to contribute to resolving this issue. I am eager to work on this. I have forked and cloned the project. Could you please provide some guidance on how to run the front end and back end of this project? Please let me know if there are any specific guidelines or steps I need to follow to get started. Thank you!

**Comment by rohinish404** [comment]
Wait for the maintainer to approve this issue..then u can start working on it:)

**Comment by devarshishimpi** [comment]
Hey @aamirxshaikh @rohinish404 This design of version is deprecated. You guys can check the new version being built with the help of Tailwind and help us there :) Looking forward to hear from you both.

https://github.com/bytemakers/Noteslify/issues/237
