### ISSUE TITLE
💡 Fix these problems

### ISSUE THREAD

**Issue by priyankarpal** [bytemakers/Noteslify#272]
### Summary

Hey, I wanna say that you made an awesome product. I have a few suggestions for this product. Please don't forget to review these.

1. I think this image is a low quality & the wave design is looking odd. 
 
![Screenshot from 2023-01-31 18-22-30](https://user-images.githubusercontent.com/88102392/215765930-35f3e765-1aed-4020-8683-c83afec1926f.png)

2.  Please fix this Newsletter design.

![Screenshot from 2023-01-31 18-22-44](https://user-images.githubusercontent.com/88102392/215766271-ce37c0b8-2c4e-493e-b82d-819f3bef17cf.png)

3. **IMPORTANT**
If anyone uses temp Email it will use it. I think it's the wrong practice.

https://user-images.githubusercontent.com/88102392/215768210-5d7316a4-203a-48b7-95c5-d68b834ca191.mp4

 
Another problem is that If anyone deletes their account after deletion it doesn't show any dialogue box.

### Basic Example

I mentioned all things also just some UI designs that need to fix.
 

### Drawbacks

Please fix the main problem[temp mail problem] otherwise it will create problems later.

**Comment by devarshishimpi** [comment]
Hey @priyankarpal This design of version is deprecated. You can check the new version being built with the help of Tailwind and help us there :) Looking forward to hear from you.

https://github.com/bytemakers/Noteslify/issues/237
