### ISSUE TITLE
🐛 [BUG] - After refreshing the page, getting error of page not found

### ISSUE THREAD

**Issue by theritikchoure** [bytemakers/Noteslify#274]
### Description

After refreshing the page, getting error of page not found error.

https://user-images.githubusercontent.com/56495602/221403706-bdb98ea5-f99e-4546-b3df-4425c386ff84.mp4

### Reproduction URL

https://noteslify.stonecss.com/notes

### Reproduction steps

```bash
1. Go to the 'Notes section or Dashboard
2. Click on the 'Refresh button from browser's top navigation
3. See the error
```

### Browsers

Microsoft Edge

### OS

Windows

**Comment by devarshishimpi** [comment]
@theritikchoure Thanks for reporting! Will update once fixed.

**Comment by devarshishimpi** [comment]
@theritikchoure Issue should be fixed now. Migrating to Vercel resolved it
