### ISSUE TITLE
🐛 [BUG] - Subscribe button not centered properly

### ISSUE THREAD

**Issue by geeky-sambhav** [bytemakers/Noteslify#284]
### Description

In the homepage at the bottom where there is Subscribe to our newsletter, The subscribe button is not centered properly.So I would like to work on this issue

![z](https://user-images.githubusercontent.com/83087385/235867924-b6f71749-bb00-4a25-9035-3e0a5ae50eb7.png)

### Reproduction URL

https://github.com/geeky-sambhav

### Reproduction steps

```bash
1. Go to 'https://noteslify.stonecss.com/'
2. Scroll down to 'Subscribe to our Newsletter component'
3. See error
```

### Browsers

Firefox, Chrome, Safari, Microsoft Edge, Opera

### OS

Windows

**Comment by geeky-sambhav** [comment]
> @geeky-sambhav Thanks for opening the issue, work for a new UI has already started in https://github.com/bytemakers/Noteslify/issues/237 Feel free to contribute there! 😄
> 
> Closing this issue..

Ok 👍🏻👍🏻

**Comment by uttam-idesign** [comment]
Should I try this?

**Comment by FazeenIjaz** [comment]
Can i do it?
