### ISSUE TITLE
Add Theming Option to the Notes and Homepage/everywhere else

### ISSUE THREAD

**Issue by devarshishimpi2** [bytemakers/Noteslify#37]
Add the options of switching themes from light to dark theme with a toggle

**Comment by khushi818** [comment]
I can do that. Let me do this as well.

**Comment by devarshishimpi** [comment]
> I can do that. Let me do this as well.

Okay, have assigned you. But were you able to self-assign yourself as you have write access?

**Comment by khushi818** [comment]
Oh do I ? I didn't check

**Comment by khushi818** [comment]
Yup I have it

**Comment by devarshishimpi** [comment]
Partially added in https://github.com/dvstechlabs/Noteslify/pull/47

**Comment by devarshishimpi** [comment]
Partial Fix in https://github.com/dvstechlabs/Noteslify/pull/89

**Comment by krishnabiradar310802** [comment]
i can add the dark mode and light mode feature

**Comment by devarshishimpi** [comment]
Assigned

**Comment by nkirukka** [comment]
I'd like to work on implementing dark mode for all pages, please assign me. Or do I need to open a new issue?

**Comment by devarshishimpi** [comment]
> I'd like to work on implementing dark mode for all pages, please assign me. Or do I need to open a new issue?

@nkirukka Hi, This issue is open and have assigned to you.

We are shifting to using Tailwind in Frontend CSS. ( Dashboard is not using Tailwind CSS, it's just the new landing page being developed for now )
You can help us out here as well 😄 https://github.com/dvstechlabs/Noteslify/issues/237

**Comment by nkirukka** [comment]
1. Which of the folders should I work in? /frontend or /frontendnew?
2. The page that opens on localhost:3000 from /frontend is different from the current live site and different from /frontendnew.

See attactment for better understanding

### Current live
![live](https://user-images.githubusercontent.com/72361299/204157342-334d727a-108c-4f6b-8d94-04a8e764ab2a.png)

### From /frontendnew
![frontendnew](https://user-images.githubusercontent.com/72361299/204157458-e36c3e41-2d99-447d-b586-382c1ee2e6f8.png)

### From /frontend
_The navbar here specifically is different_
![frontend](https://user-images.githubusercontent.com/72361299/204157548-efde5bbb-10eb-4afb-b23a-4f9ce5ec97f1.png)

**Comment by devarshishimpi** [comment]
@nkirukka 

> Which of the folders should I work in? /frontend or /frontendnew?

`frontendnew`

> The page that opens on localhost:3000 from /frontend is different from the current live site and different from /frontendnew.

Yes, since it's not running the latest version due to some under-development features like the folders section.
The older frontend landing page is no-longer developed. ( Only the landing page )
![image](https://user-images.githubusercontent.com/43378923/204265769-73899efe-42b2-48b4-9a23-8c0bbc27cc69.png)

> Is there a color guide for dark theme or do I have creative liberty?

Nothing specific for dark theme. Feel free to use what you think the best!!!

**Comment by devarshishimpi** [comment]
@nkirukka You can start working on it 🎉 

Also, Could you make it in such a way that only adding the prefix `dark:` to any style element selects the dark theme for that element, for example, I wanted to make a title white in the dark theme and black in light theme, so I should be able to use `<style="text-black dark:text-white">` Hope you get my point! And then you can continue to implement dark theme on all the pages!

**Comment by devarshishimpi** [comment]
@nkirukka Updates?

**Comment by thevinitgupta** [comment]
Can I start working on this?

**Comment by devarshishimpi** [comment]
> Can I start working on this?

Sure @thevinitgupta Have assigned you the same.

**Comment by thevinitgupta** [comment]
> Also, Could you make it in such a way that only adding the prefix `dark:` to any style element selects the dark theme for that element, for example, I wanted to make a title white in the dark theme and black in light theme, so I should be able to use `<p className="text-black dark:text-white">Some Text</p>`

@devarshishimpi I have configured `tailwind` to do this as you asked.
But the pages accessible (like Pricing, Features) already have the dark mode options
While the Signup and Contact pages don't have any content. 

Could you please clarify?

**Comment by devarshishimpi** [comment]
> > Also, Could you make it in such a way that only adding the prefix `dark:` to any style element selects the dark theme for that element, for example, I wanted to make a title white in the dark theme and black in light theme, so I should be able to use `<p className="text-black dark:text-white">Some Text</p>`
> 
> @devarshishimpi I have configured `tailwind` to do this as you asked. But the pages accessible (like Pricing, Features) already have the dark mode options While the Signup and Contact pages don't have any content.
> 
> Could you please clarify?

Yes, that's great. You can raise a PR for the same. Sign-up and Contact Pages haven't been made yet.

**Comment by devarshishimpi** [comment]
Fixed! Thanks to @thevinitgupta and @nkirukka 🎉
